/* 
 * [DMC Master List] - Partial Database
 * This file acts as the GROUND TRUTH for official DMC floss numbers.
 * The purpose is to explicitly stop using fake/hallucinated DMC colors.
 * IMPORTANT: DO NOT add fake entries to this file. 
 * If a DMC color is not verifiable as official, DO NOT ADD IT HERE.
 */

export const DMC_MASTER = [
    // Special
    { dmcNumber: "BLANC", nameEn: "White", hex: "#FFFFFF" },
    { dmcNumber: "ECRU", nameEn: "Ecru", hex: "#F0EAD6" },
    { dmcNumber: "B5200", nameEn: "Snow White", hex: "#FFFFFF" },

    // Official 150~169 series (Partial)
    { dmcNumber: "150", nameEn: "Dusty Rose-UL VY DK", hex: "#AB0203" },
    { dmcNumber: "151", nameEn: "Dusty Rose-VY LT", hex: "#F0CECE" },
    { dmcNumber: "152", nameEn: "Shell Pink-MD LT", hex: "#E2A8A8" },
    { dmcNumber: "153", nameEn: "Violet-VY LT", hex: "#E0CCEB" },
    { dmcNumber: "154", nameEn: "Grape-VY DK", hex: "#2D1B2E" },
    { dmcNumber: "155", nameEn: "Forget-me-not Blue-DK", hex: "#6A77A1" },
    { dmcNumber: "156", nameEn: "Blue Violet-MD LT", hex: "#9D91C4" },
    { dmcNumber: "157", nameEn: "Cornflower Blue-VY LT", hex: "#BBC7DE" },
    { dmcNumber: "158", nameEn: "Cornflower Blue-MD VY DK", hex: "#3B4E7A" },
    { dmcNumber: "159", nameEn: "Gray Blue-LT", hex: "#C7C9D6" },
    { dmcNumber: "160", nameEn: "Gray Blue-MD", hex: "#959BAE" },
    { dmcNumber: "161", nameEn: "Gray Blue", hex: "#737A92" },
    { dmcNumber: "162", nameEn: "Blue-UL VY LT", hex: "#DBE7ED" },
    { dmcNumber: "163", nameEn: "Celadon Green-MD", hex: "#6A9176" },
    { dmcNumber: "164", nameEn: "Forest Green-LT", hex: "#C6D6BB" },
    { dmcNumber: "165", nameEn: "Moss Green-VY LT", hex: "#E6EDB7" },
    { dmcNumber: "166", nameEn: "Moss Green-MD LT", hex: "#C1CF7A" },
    { dmcNumber: "167", nameEn: "Yellow Beige-VY DK", hex: "#A88858" },
    { dmcNumber: "168", nameEn: "Pewter-VY LT", hex: "#D1D1D1" },
    { dmcNumber: "169", nameEn: "Pewter-LT", hex: "#8A9196" },

    // Official 200~300 series (Partial subset)
    { dmcNumber: "208", nameEn: "Lavender-VY DK", hex: "#83528A" },
    { dmcNumber: "209", nameEn: "Lavender-DK", hex: "#BC8AC9" },
    { dmcNumber: "210", nameEn: "Lavender-MD", hex: "#DABBDF" },
    { dmcNumber: "211", nameEn: "Lavender-LT", hex: "#E6CEE6" },
    { dmcNumber: "221", nameEn: "Shell Pink-VY DK", hex: "#883D43" },
    { dmcNumber: "223", nameEn: "Shell Pink-LT", hex: "#CC7C80" },
    { dmcNumber: "224", nameEn: "Shell Pink-VY LT", hex: "#E9B2B6" },
    { dmcNumber: "225", nameEn: "Shell Pink-UL VY LT", hex: "#FFE1E4" },

    // Official 300 series (Partial subset)
    { dmcNumber: "300", nameEn: "Mahogany-VY DK", hex: "#683011" },
    { dmcNumber: "301", nameEn: "Mahogany-MD", hex: "#B35A1F" },
    { dmcNumber: "304", nameEn: "Red-MD", hex: "#B62234" },
    { dmcNumber: "307", nameEn: "Lemon", hex: "#FEF65B" },
    { dmcNumber: "309", nameEn: "Rose-DK", hex: "#BA274A" },
    { dmcNumber: "310", nameEn: "Black", hex: "#000000" },
    { dmcNumber: "311", nameEn: "Navy Blue-MD", hex: "#1C538E" },
    { dmcNumber: "312", nameEn: "Baby Blue-VY DK", hex: "#1E476B" },
    { dmcNumber: "315", nameEn: "Antique Mauve-VY DK", hex: "#865258" },
    { dmcNumber: "316", nameEn: "Antique Mauve-MD", hex: "#A87884" },
    { dmcNumber: "317", nameEn: "Pewter Gray", hex: "#6E6F72" },
    { dmcNumber: "318", nameEn: "Steel Gray-LT", hex: "#B8B8B8" },
    { dmcNumber: "319", nameEn: "Pistachio Green-VY DK", hex: "#275533" },
    { dmcNumber: "320", nameEn: "Pistachio Green-MD", hex: "#6C8B6E" },
    { dmcNumber: "321", nameEn: "Red", hex: "#C72B3B" },
    { dmcNumber: "322", nameEn: "Baby Blue-DK", hex: "#5D8CAE" },
    { dmcNumber: "326", nameEn: "Rose-VY DK", hex: "#99213D" },
    { dmcNumber: "327", nameEn: "Violet-DK", hex: "#6A3268" },
    { dmcNumber: "333", nameEn: "Blue Violet-VY DK", hex: "#5C4589" },
    { dmcNumber: "334", nameEn: "Baby Blue-MD", hex: "#739FC1" },
    { dmcNumber: "335", nameEn: "Rose", hex: "#EE547A" },
    { dmcNumber: "336", nameEn: "Navy Blue", hex: "#142851" },
    { dmcNumber: "340", nameEn: "Blue Violet-MD", hex: "#9D91C4" },
    { dmcNumber: "341", nameEn: "Blue Violet-LT", hex: "#B7B0D8" },
    { dmcNumber: "347", nameEn: "Salmon-VY DK", hex: "#BF2D2D" },
    { dmcNumber: "349", nameEn: "Coral-DK", hex: "#D21E2C" },
    { dmcNumber: "350", nameEn: "Coral-MD", hex: "#E04848" },
    { dmcNumber: "351", nameEn: "Coral", hex: "#E96A67" },
    { dmcNumber: "352", nameEn: "Coral-LT", hex: "#FD9C97" },
    { dmcNumber: "353", nameEn: "Peach", hex: "#FDCFB8" },
    { dmcNumber: "355", nameEn: "Rust-DK", hex: "#944633" },
    { dmcNumber: "356", nameEn: "Rust-MD", hex: "#C0614C" },
    { dmcNumber: "367", nameEn: "Pistachio Green-DK", hex: "#4F6B55" },
    { dmcNumber: "368", nameEn: "Pistachio Green-LT", hex: "#A0BC9E" },
    { dmcNumber: "369", nameEn: "Pistachio Green-VY LT", hex: "#C9DEC4" },
    { dmcNumber: "370", nameEn: "Mustard-MD", hex: "#AC8F62" },
    { dmcNumber: "371", nameEn: "Mustard", hex: "#94805A" },
    { dmcNumber: "372", nameEn: "Mustard-LT", hex: "#BBAF88" },

    // Official 400 series (Partial subset)
    { dmcNumber: "400", nameEn: "Mahogany-DK", hex: "#85401A" },
    { dmcNumber: "402", nameEn: "Mahogany-VY LT", hex: "#EAA87E" },
    { dmcNumber: "407", nameEn: "Desert Sand-DK", hex: "#AB705B" },
    { dmcNumber: "413", nameEn: "Pewter Gray-DK", hex: "#565656" },
    { dmcNumber: "414", nameEn: "Steel Gray-DK", hex: "#8C8C8C" },
    { dmcNumber: "415", nameEn: "Pearl Gray", hex: "#D3D3D6" },
    { dmcNumber: "420", nameEn: "Hazelnut Brown-DK", hex: "#8C5D36" },
    { dmcNumber: "422", nameEn: "Hazelnut Brown-LT", hex: "#C69F7B" },
    { dmcNumber: "433", nameEn: "Brown-MD", hex: "#7A4325" },
    { dmcNumber: "434", nameEn: "Brown-LT", hex: "#9C5B36" },
    { dmcNumber: "435", nameEn: "Brown-VY LT", hex: "#B8754A" },
    { dmcNumber: "436", nameEn: "Tan", hex: "#CF9F76" },
    { dmcNumber: "437", nameEn: "Tan-LT", hex: "#E2B895" },
    { dmcNumber: "444", nameEn: "Lemon-DK", hex: "#FFD600" },
    { dmcNumber: "445", nameEn: "Lemon-LT", hex: "#FFFFA6" },
    { dmcNumber: "451", nameEn: "Shell Gray-DK", hex: "#8E7C74" },
    { dmcNumber: "452", nameEn: "Shell Gray-MD", hex: "#BCAFA6" },
    { dmcNumber: "453", nameEn: "Shell Gray-LT", hex: "#D2C5BD" },

    // --- VERIFIED ADDITIONS ---
    { dmcNumber: "151", nameEn: "Dusty Rose-VY LT", hex: "#F0CECE" },
    { dmcNumber: "152", nameEn: "Shell Pink-MD LT", hex: "#E2A6A6" },
    { dmcNumber: "153", nameEn: "Violet-VY LT", hex: "#E0CCD8" },
    { dmcNumber: "155", nameEn: "Blue Violet-MD DK", hex: "#9884B9" },
    { dmcNumber: "156", nameEn: "Blue Violet-MD LT", hex: "#A3ADD2" },
    { dmcNumber: "157", nameEn: "Cornflower Blue-VY LT", hex: "#BBC5DD" },
    { dmcNumber: "158", nameEn: "Cornflower Blue-MD VY DK", hex: "#4C547C" },
    { dmcNumber: "159", nameEn: "Gray Blue-LT", hex: "#C7CEDB" },
    { dmcNumber: "160", nameEn: "Gray Blue-MD", hex: "#99A5B8" },
    { dmcNumber: "161", nameEn: "Gray Blue", hex: "#7A88A1" },
    { dmcNumber: "162", nameEn: "Blue-UL VY LT", hex: "#DCEBF3" },
    { dmcNumber: "163", nameEn: "Celadon Green-MD", hex: "#5C8F70" },
    { dmcNumber: "164", nameEn: "Forest Green-LT", hex: "#C7DCA6" },
    { dmcNumber: "165", nameEn: "Moss Green-VY LT", hex: "#E2EDA3" },
    { dmcNumber: "166", nameEn: "Moss Green-MD LT", hex: "#C1D54F" },
    { dmcNumber: "167", nameEn: "Yellow Beige-VY DK", hex: "#8A6D47" },
    { dmcNumber: "168", nameEn: "Pewter-VY LT", hex: "#D1D1D1" },
    { dmcNumber: "169", nameEn: "Pewter-LT", hex: "#8F8F8F" },
    { dmcNumber: "221", nameEn: "Shell Pink-VY DK", hex: "#883E46" },
    { dmcNumber: "223", nameEn: "Shell Pink-LT", hex: "#CB8081" },
    { dmcNumber: "224", nameEn: "Shell Pink-VY LT", hex: "#E7B8B5" },
    { dmcNumber: "225", nameEn: "Shell Pink-UL VY LT", hex: "#FFDFD9" },
    { dmcNumber: "300", nameEn: "Mahogany-VY DK", hex: "#733309" },
    { dmcNumber: "304", nameEn: "Christmas Red-MD", hex: "#B51A31" },
    { dmcNumber: "309", nameEn: "Rose-DK", hex: "#BA2547" },
    { dmcNumber: "316", nameEn: "Antique Mauve", hex: "#B87F8B" },
    { dmcNumber: "320", nameEn: "Pistachio Green-MD", hex: "#6E936B" },
    { dmcNumber: "326", nameEn: "Rose-VY DK", hex: "#9F1936" },
    { dmcNumber: "334", nameEn: "Baby Blue-MD", hex: "#739FC1" },
    { dmcNumber: "335", nameEn: "Rose", hex: "#EE547A" },
    { dmcNumber: "355", nameEn: "Terra Cotta-DK", hex: "#A83E31" },
    { dmcNumber: "356", nameEn: "Terra Cotta-MD", hex: "#C96A59" },
    { dmcNumber: "367", nameEn: "Pistachio Green-DK", hex: "#50714E" },
    { dmcNumber: "368", nameEn: "Pistachio Green-LT", hex: "#A6C2A0" },
    { dmcNumber: "369", nameEn: "Pistachio Green-VY LT", hex: "#D6E5D1" },
    { dmcNumber: "370", nameEn: "Mustard-MD", hex: "#B18D68" },
    { dmcNumber: "371", nameEn: "Mustard", hex: "#C6A478" },
    { dmcNumber: "372", nameEn: "Mustard-LT", hex: "#D6BA91" },
    { dmcNumber: "400", nameEn: "Mahogany-DK", hex: "#8F4316" },
    { dmcNumber: "402", nameEn: "Mahogany-VY LT", hex: "#F3AA7F" },

    // --- SECOND BATCH VERIFIED ADDITIONS ---
    { dmcNumber: "151", nameEn: "Dusty Rose-VY LT", hex: "#F0CECE" },
    { dmcNumber: "152", nameEn: "Shell Pink-MD LT", hex: "#E2A6A6" },
    { dmcNumber: "153", nameEn: "Violet-VY LT", hex: "#E0CCD8" },
    { dmcNumber: "422", nameEn: "Hazelnut Brown-LT", hex: "#C69F7B" },
    { dmcNumber: "433", nameEn: "Brown-MD", hex: "#7A4323" },
    { dmcNumber: "435", nameEn: "Brown-VY LT", hex: "#B87544" },
    { dmcNumber: "437", nameEn: "Tan-LT", hex: "#E8B78D" },
    { dmcNumber: "445", nameEn: "Lemon-LT", hex: "#FFFF99" },
    { dmcNumber: "451", nameEn: "Shell Gray-DK", hex: "#8D7C7A" },
    { dmcNumber: "452", nameEn: "Shell Gray-MD", hex: "#A89A98" },
    { dmcNumber: "453", nameEn: "Shell Gray-LT", hex: "#C7BEBC" },
    { dmcNumber: "469", nameEn: "Avocado Green", hex: "#5C6A3C" },
    { dmcNumber: "470", nameEn: "Avocado Green-LT", hex: "#748849" },
    { dmcNumber: "471", nameEn: "Avocado Green-VY LT", hex: "#95A869" },
    { dmcNumber: "472", nameEn: "Avocado Green-UL LT", hex: "#D8E498" },
    { dmcNumber: "580", nameEn: "Moss Green-DK", hex: "#4C6B28" },
    { dmcNumber: "581", nameEn: "Moss Green", hex: "#728F3F" },
    { dmcNumber: "597", nameEn: "Turquoise", hex: "#4B8B9B" },
    { dmcNumber: "598", nameEn: "Turquoise-LT", hex: "#90C0C8" },
    { dmcNumber: "601", nameEn: "Cranberry-DK", hex: "#D03568" },
    { dmcNumber: "602", nameEn: "Cranberry-MD", hex: "#DE497D" },
    { dmcNumber: "603", nameEn: "Cranberry", hex: "#EE6A9B" },
    { dmcNumber: "604", nameEn: "Cranberry-LT", hex: "#F59BBF" },
    { dmcNumber: "605", nameEn: "Cranberry-VY LT", hex: "#FFC2D9" },
    { dmcNumber: "608", nameEn: "Bright Orange", hex: "#FD4F1A" },
    { dmcNumber: "610", nameEn: "Drab Brown-DK", hex: "#765C45" },
    { dmcNumber: "611", nameEn: "Drab Brown", hex: "#907357" },
    { dmcNumber: "612", nameEn: "Drab Brown-LT", hex: "#A88D70" },
    { dmcNumber: "613", nameEn: "Drab Brown-VY LT", hex: "#C7B29A" },
    { dmcNumber: "632", nameEn: "Desert Sand-UL VY DK", hex: "#824536" },
    { dmcNumber: "640", nameEn: "Beige Gray-VY DK", hex: "#837666" },
    { dmcNumber: "642", nameEn: "Beige Gray-DK", hex: "#A39785" },
    { dmcNumber: "644", nameEn: "Beige Gray-MD", hex: "#D1C9BB" },
    { dmcNumber: "645", nameEn: "Beaver Gray-VY DK", hex: "#6E6864" },
    { dmcNumber: "646", nameEn: "Beaver Gray-DK", hex: "#857D78" },
    { dmcNumber: "647", nameEn: "Beaver Gray-MD", hex: "#B0A9A3" },
    { dmcNumber: "648", nameEn: "Beaver Gray-LT", hex: "#C6BFB9" },
    { dmcNumber: "676", nameEn: "Old Gold-LT", hex: "#E4BA73" },
    { dmcNumber: "677", nameEn: "Old Gold-VY LT", hex: "#F3DEAC" },
    { dmcNumber: "680", nameEn: "Old Gold-DK", hex: "#B88A3D" },

    // --- FOURTH BATCH VERIFIED ADDITIONS ---
    { dmcNumber: "699", nameEn: "Green-MD", hex: "#0B7A38" },
    { dmcNumber: "712", nameEn: "Cream", hex: "#FBF3E4" },
    { dmcNumber: "730", nameEn: "Olive Green-VY DK", hex: "#685E31" },
    { dmcNumber: "732", nameEn: "Olive Green", hex: "#746937" },
    { dmcNumber: "733", nameEn: "Olive Green-MD", hex: "#8B8045" },
    { dmcNumber: "734", nameEn: "Olive Green-LT", hex: "#B8AD72" },
    { dmcNumber: "738", nameEn: "Tan-VY LT", hex: "#E9C9A6" },
    { dmcNumber: "739", nameEn: "Tan-UL VY LT", hex: "#F5E4D1" },
    { dmcNumber: "742", nameEn: "Tangerine-LT", hex: "#FFB547" },
    { dmcNumber: "743", nameEn: "Yellow-MD", hex: "#FCD66F" },
    { dmcNumber: "744", nameEn: "Yellow-Pale", hex: "#FFE692" },
    { dmcNumber: "745", nameEn: "Yellow-LT Pale", hex: "#FFF0B8" },
    { dmcNumber: "746", nameEn: "Off White", hex: "#FCF8E9" },
    { dmcNumber: "747", nameEn: "Sky Blue-VY LT", hex: "#E1F0F4" },
    { dmcNumber: "754", nameEn: "Peach-LT", hex: "#F6C8B5" },
    { dmcNumber: "758", nameEn: "Terra Cotta-VY LT", hex: "#EEAA95" },
    { dmcNumber: "760", nameEn: "Salmon", hex: "#F59CA2" },
    { dmcNumber: "761", nameEn: "Salmon-LT", hex: "#FFC5C9" },
    { dmcNumber: "762", nameEn: "Pearl Gray-VY LT", hex: "#ECECEC" },
    { dmcNumber: "772", nameEn: "Yellow Green-VY LT", hex: "#DDE7C1" },
    { dmcNumber: "775", nameEn: "Baby Blue-VY LT", hex: "#D6E4EE" },
    { dmcNumber: "777", nameEn: "Raspberry-VY DK", hex: "#911D36" },
    { dmcNumber: "778", nameEn: "Antique Mauve-VY LT", hex: "#DFAAB4" },
    { dmcNumber: "779", nameEn: "Cocoa-DK", hex: "#634743" },
    { dmcNumber: "780", nameEn: "Topaz-UL VY DK", hex: "#8A511B" },
    { dmcNumber: "781", nameEn: "Topaz-VY DK", hex: "#A36323" },
    { dmcNumber: "782", nameEn: "Topaz-DK", hex: "#BB772E" },
    { dmcNumber: "783", nameEn: "Topaz-MD", hex: "#D69038" },
    { dmcNumber: "791", nameEn: "Cornflower Blue-VY DK", hex: "#353265" },
    { dmcNumber: "792", nameEn: "Cornflower Blue-DK", hex: "#525791" },
    { dmcNumber: "793", nameEn: "Cornflower Blue-MD", hex: "#7281AE" },
    { dmcNumber: "794", nameEn: "Cornflower Blue-LT", hex: "#9DAAD2" },
    { dmcNumber: "798", nameEn: "Delft Blue-DK", hex: "#3E5C8D" },
    { dmcNumber: "799", nameEn: "Delft Blue-MD", hex: "#6384B7" },
    { dmcNumber: "800", nameEn: "Delft Blue-Pale", hex: "#C0D2E9" },
    { dmcNumber: "801", nameEn: "Coffee Brown-DK", hex: "#5D3723" },
    { dmcNumber: "803", nameEn: "Baby Blue-UL VY DK", hex: "#223E63" },
    { dmcNumber: "806", nameEn: "Peacock Blue-DK", hex: "#337691" },
    { dmcNumber: "807", nameEn: "Peacock Blue", hex: "#4895AE" },
    { dmcNumber: "809", nameEn: "Delft Blue", hex: "#8DA7D0" }
];
